const BANI_LANGS = ["uk", "ru", "en"];

const BANI_I18N = {
  ru: {
    "app.title": "Банки",
    "app.tag": "Перелей цвет. Не оставь себя без хода.",
    "you": "Ты",
    "you.letter": "Я",
    "rival": "Соперник",
    "on": "Вкл",
    "off": "Выкл",
    "back": "Назад",
    "menu": "Меню",
    "home": "На главный",
    "settings": "Настройки",
    "premium": "Премиум",
    "skins": "Скины",
    "play": "Играть",
    "toGame": "К игре",
    "toMenu": "В меню",
    "close": "Закрыть",
    "next": "Дальше",
    "gotIt": "Понятно",
    "start": "Начать",
    "claim": "Забрать",
    "levelShort": "ур. {n}",
    "tower": "Башня",
    "tower.hold": "Попробуй удержать первое место",
    "tower.until": "до приза",
    "packs": "Наборы",
    "packs.sub": "Монеты и бомбы",
    "packs.banner": "Наборы",
    "packs.uah": "Наборы за гривны",
    "packs.uahSub": "Монеты, бомбы и жирный огонёк",
    "packs.vitrine": "Витрина",
    "hint": "Подсказка",
    "undo": "Отмена",
    "restart": "Заново",
    "skinBtn": "Скин банки",
    "skinHud": "Скин: {name}",
    "more": "Ещё игры — пилот студии",
    "hud.bomb": "Звёзды наполняют бомбу. 100 ★ = 💣",
    "hud.fire": "Заходи каждый день. Огонёк умножает выигрыш",
    "hud.tower": "Башня",
    "set.lead": "Как тебе удобнее играть.",
    "set.leadQuiet": "Эффекты выключены — поле спокойнее.",
    "set.lang": "Язык",
    "set.langSub": "Тексты в игре",
    "set.sound": "Звук",
    "set.soundSub": "Капли и победа",
    "set.vibe": "Вибрация",
    "set.vibeSub": "Отдача в руке",
    "set.juice": "Эффекты",
    "set.juiceSub": "Брызги и вспышки. Выключи, если тормозит",
    "set.hint": "Подсказка на старте",
    "set.hintSub": "Первая банка чуть подпрыгнет",
    "set.skin": "Скин банок",
    "set.catalog": "Каталог",
    "set.reset": "Сбросить прогресс",
    "set.resetSub": "Уровни, монеты, скины — сначала",
    "set.erase": "Стереть",
    "set.sure": "Точно?",
    "win.got": "Есть!",
    "win.done": "Собрал",
    "win.more": "Дальше больше цветов и длиннее ходы.",
    "win.double": "Ролик — удвоить",
    "win.doubleFree": "Без рекламы — удвоить",
    "win.wait": "Секунду…",
    "win.ad": "Ролик…",
    "win.doubled": "Удвоено",
    "win.share": "Показать",
    "win.tower": "Башня",
    "win.crown": "Корона твоя",
    "win.point": "Плюс 1 балл. Ты #{place}. До {name} ещё {n}.",
    "win.first": "Плюс 1 балл. Ты первый на неделе. Сундук твой, если удержишь.",
    "win.stage": "Этап закрыт.",
    "win.toChest": "{n} / 100 до сундука.",
    "win.bombReady": " Бомба готова!",
    "win.next": "Следующий",
    "win.newChapter": "Новая глава",
    "win.fromOne": "С первого",
    "win.again": "Ещё бой",
    "win.story": "В историю",
    "fail.almost": "Почти",
    "fail.stuck": "Тупик",
    "fail.almostText": "Ещё одна банка — и цвет закрылся бы. Ты сам долил до края.",
    "fail.stuckText": "Хода нет. Сам собрал ловушку — это и есть «ещё чуть-чуть».",
    "fail.risk": "Огонёк не сгорает здесь. Он растёт, если заходишь каждый день.",
    "fail.undo": "Отменить ход",
    "fail.jar": "Ещё банка",
    "fail.keep": "Заново, серия жива",
    "fail.keepPay": "Заново, серия {n} ",
    "fail.give": "Сдаться — серия сгорит",
    "fail.open": "Открыть банку ",
    "fail.openOk": "Банки открыты",
    "lock.title": "Закрытая банка",
    "lock.broken": "Сломанная банка",
    "lock.frozen": "Замороженная банка",
    "lock.text": "Пустое место. Откроешь — будет куда лить, когда тесно.",
    "lock.open": "Открыть",
    "lock.charge": "Своя колба",
    "lock.chargeN": "Своя колба · {n}",
    "lock.ad": "Ролик — открыть",
    "lock.later": "Пока нет",
    "lock.playSo": "Играть так",
    "lock.fix": "Починить ",
    "lock.thaw": "Разморозить ",
    "lock.adFix": "Ролик — починить",
    "lock.adThaw": "Ролик — разморозить",
    "lock.freeOpen": "Без рекламы — открыть",
    "lock.freeFix": "Без рекламы — починить",
    "lock.freeThaw": "Без рекламы — разморозить",
    "lock.woundBomb": "У тебя сломана банка. Это {name}. Почини за монеты или ролик.",
    "lock.woundFreeze": "У тебя заморожена банка. Это {name}. Разморозь за монеты или ролик.",
    "lock.mustPaint": " Банка с краской — чинить обязательно.",
    "lock.tight": "Уровень тесный. Без колбы некуда лить.",
    "lock.last": "Последняя закрытая. Откроешь — появится пустое место.",
    "lock.more": "Ещё {n} закрытых. Сначала одну.",
    "lock.pour": " Откроешь — можно лить дальше.",
    "lock.hinder": " Часть замков — помеха башни на эту неделю.",
    "league.title": "Лига недели",
    "league.lead": "Одни и те же соперники до понедельника. Не онлайн-чат.",
    "league.shop": "Магазин монет",
    "league.race": "Забег",
    "map.lead": "Собирай монеты и звёзды для главного сундука в башне тут",
    "map.stage": "Сотня {n}. Те же 100, уже злее.",
    "pass.title": "Башня на замке",
    "pass.call": "Сундук недели только для тех, кто накопил на вход",
    "pass.wallet": "В кошельке",
    "pass.need": "Вход — 1000 монет",
    "pass.miss": "Не хватает монет",
    "pass.short": "Не хватает {n} монет",
    "pass.ok": "Монет хватает — можно войти",
    "pass.buy": "Купить пропуск ",
    "pass.shop": "В магазин",
    "prize.kicker": "В сундуке недели",
    "tower.score": "Твои очки: {n}",
    "tower.scorePlace": "Твои очки: {n} · #{place}",
    "shop.title": "Магазин монет",
    "shop.lead": "Трать на колбы и на помеху другим. Ролик — только если сам включил.",
    "shop.skins": "Скины банок",
    "shop.skinsSub": "20 видов. Премиум — за монеты",
    "shop.flask": "Запасная колба",
    "shop.flaskSub": "Откроет закрытую банку без цены уровня",
    "shop.seal": "Печать на колбу",
    "shop.sealSub": "Обычные монеты. Остановит рост очков",
    "shop.undo": "Пачка отмен",
    "shop.undoSub": "Две отмены в карман",
    "shop.ad": "Ролик — монеты",
    "shop.watch": "Смотреть",
    "shop.take": "Забрать",
    "shop.adFor": " за просмотр",
    "shop.adFree": " без ролика",
    "shop.have": "У тебя ",
    "shop.have2": " {coins} и {n} запасных колб.",
    "skins.title": "Скины",
    "skins.lead": "Восемь простых из сундуков. Двенадцать премиум — за монеты.",
    "skins.have": "У тебя {owned} / 20. Премиум {prem} / 12. Монет {coins}.",
    "chest.title": "Сундук главы",
    "chest.lead": "За десять уровней. Вот что внутри.",
    "chest.prizeLead": "Приз за {n} уровней.",
    "jack.title": "Ты первый!",
    "jack.lead": "Неделя закрыта. Этот приз твой.",
    "jack.word": "за первое место",
    "intro.stars": "Звёзды",
    "intro.starsText": "Собирай звёзды, чтобы получить бомбу. Каждые 100 звёзд наполняют ёмкость — в башне бомбой можно разорвать колбу противнику.",
    "intro.fire": "Огонёк",
    "intro.fireText": "Это буст к заработку. Заходи каждый день — не потеряй буст. Каждый день огонёк +1. С выигрыша монет: умножение на 0,1 × число огоньков.",
    "intro.coins": "Монеты и подсказка",
    "intro.coinsText": "Монетки — на покупки. Лампочка — подсказка хода. Это и так видно в шапке.",
    "time.dh": "{d}д {h}ч",
    "time.hm": "{h}ч {m}м",
    "time.m": "{m} мин",
    "time.home": "{left} до приза",
    "day.1": "день",
    "day.2": "дня",
    "day.5": "дней",
    "league.days": "Ещё {n} {word} до новой сетки. Соперники недели, не живой чат.",
    "race.done": "Забег ур. {n} · {stars}★ / {moves}",
    "race.wait": "Забег недели · уровень {n}",
    "hinder.1": "Помеха недели: закрыто {n} колба.",
    "hinder.n": "Помеха недели: закрыто {n} колбы.",
    "floor": "этаж",
    "track.tower": "#{place} · очки до понедельника",
    "track.towerEmpty": "Очки башни",
    "skin.worn": "надет",
    "skin.yours": "твой",
    "skin.chest": "сундук",
    "skin.default": "Стекло",
    "skin.night": "Ночь",
    "skin.mint": "Мята",
    "skin.rose": "Роза",
    "skin.sand": "Песок",
    "skin.ice": "Лёд",
    "skin.smoke": "Дым",
    "skin.foam": "Пена",
    "skin.ribbed": "Рефлёные",
    "skin.vase": "Вазы",
    "skin.mug": "Кружки",
    "skin.wide": "Широкие",
    "skin.gold": "Золото",
    "skin.honey": "Мёд",
    "skin.ocean": "Океан",
    "skin.ember": "Уголь",
    "skin.lava": "Лава",
    "skin.neon": "Неон",
    "skin.crystal": "Кристалл",
    "skin.ink": "Тушь",
    "skin.aurora": "Сияние",
    "skin.royal": "Корона",
    "skin.void": "Пустота",
    "skin.myth": "Миф",
    "ch.0": "Первые банки",
    "ch.1": "Три цвета",
    "ch.2": "Вкус победы",
    "ch.3": "Тесно",
    "ch.4": "Четыре в ряд",
    "ch.5": "Пять красок",
    "ch.6": "Давление",
    "ch.7": "Жара",
    "ch.8": "Шесть цветов",
    "ch.9": "Корона",
    "pack.pack200": "Старт",
    "pack.pack500": "Запас",
    "pack.pack999": "Корона",
    "pack.coins": "монеты",
    "pack.bombs": "бомбы",
    "pack.fire": "огонёк",
    "pack.grn": " грн",
    "pack.loot": "{coins} монет · {bombs} бомб",
    "pack.lootFire": "{coins} монет · {bombs} бомб · огонёк ×2",
    "jack.mute": "Неделя без рекламы",
    "jack.mute.sub": "Ни одного ролика. Только банки.",
    "jack.bombs": "Бомбы без дна",
    "jack.bombs.sub": "14 дней кидай сколько влезет.",
    "jack.hints": "Подсказки без конца",
    "jack.hints.sub": "Две недели любая банка светится.",
    "jack.coins": "100 000 монет",
    "jack.coins.sub": "Гора. Хватит на башню и все банки.",
    "jack.fire": "Огонёк ×5",
    "jack.fire.sub": "Неделя. Каждый выигрыш жирный.",
    "jack.skins": "Все скины сразу",
    "jack.skins.sub": "Золото, лава, миф — твои.",
    "jack.mix": "Джекпот недели",
    "jack.mix.sub": "25 000 монет, бомбы ∞ на 7 дней и огонь ×3.",
    "loot.hints": "{n} подсказок",
    "loot.skin": "Скин «{name}»",
    "loot.coins": "+{n} монет",
    "loot.boost": "×{mult} монет на {hours} часа",
    "loot.stage": "Новая сотня: те же 100, уже сложнее",
    "loot.skinJar": "Скин «{name}» — вид банок",
    "word.hint1": "подсказка",
    "word.hint2": "подсказки",
    "word.hint5": "подсказок",
    "word.coins": "монет",
    "word.hours": "на {n} ч",
    "word.skin": "Скин",
    "word.jars": "банок",
    "word.levels": "уровней",
    "word.undo1": "отмена",
    "word.undoN": "отмен",
    "word.prize": "Приз",
    "word.chest": "сундук",
    "toast.reset": "Прогресс сброшен",
    "toast.stage": "Сотня {n}. Уже теснее.",
    "toast.wear": "Надел «{name}»",
    "toast.skinChest": "«{name}» падает из сундука главы",
    "toast.needCoins": "Нужно {n} монет",
    "toast.bought": "Купил «{name}»",
    "toast.jackpot": "Приз башни у тебя",
    "toast.needPass": "Нужно 1000 монет. Играй уровни — копи.",
    "toast.pass": "Пропуск на неделю твой. Можно соревноваться.",
    "toast.payFail": "Оплата не прошла",
    "toast.packTest": "Набор «{name}» твой. Когда выйдет в Play — {uah} грн.",
    "toast.packOk": "Набор «{name}» твой.",
    "toast.sealTap": "Жми печать на игроке.",
    "toast.sealPay": "Печать — за монеты.",
    "toast.bombTap": "Жми бомбу на игроке.",
    "toast.bombNeed": "Собери звёзды, чтобы получить бомбу.",
    "toast.flask": "Запасная колба +1",
    "toast.adFail": "Реклама не открылась",
    "toast.lockFirst": "Сначала пройди уровень {n}",
    "toast.noEmpty": "Пустых нет. Колба или ролик.",
    "toast.sealHit": "У {name} заморожена банка",
    "toast.bombHit": "У {name} сломана банка",
    "toast.adCoins": "+{n} монет",
    "wound.paintBomb": "У тебя банка с краской сломана. Это {name}. Чинить обязательно.",
    "wound.paintFreeze": "У тебя банка с краской заморожена. Это {name}. Чинить обязательно.",
    "wound.bomb": "У тебя сломана банка. Это {name}",
    "wound.freeze": "У тебя заморожена банка. Это {name}",
    "wound.must": "банка с краской — чинить обязательно",
    "wound.jar": "банка {n}",
    "aria.bomb": "Бомба",
    "aria.seal": "Печать",
    "aria.locked": "закрытая банка",
    "aria.pack": "Набор «{name}» · {uah} грн",
    "tip.bomb": "Бомба ломает ему банку. Бомбы копятся из звёзд.",
    "tip.seal": "Печать замораживает ему банку. Платишь монетами.",
    "share.line": "Глава «{ch}» · уровень {n} · серия {streak} · лига #{place}",
    "share.chapter": "Глава",
    "share.level": "Уровень {n}",
    "share.streak": "Серия {n}",
    "share.league": "Лига #{n}",
    "share.foot": "Сам собрал. Без подсказки на скрине.",
  },
  uk: {
    "app.title": "Банки",
    "app.tag": "Перелий колір. Не лиши себе без ходу.",
    "you": "Ти",
    "you.letter": "Я",
    "rival": "Суперник",
    "on": "Увімк",
    "off": "Вимк",
    "back": "Назад",
    "menu": "Меню",
    "home": "На головну",
    "settings": "Налаштування",
    "premium": "Преміум",
    "skins": "Скіни",
    "play": "Грати",
    "toGame": "До гри",
    "toMenu": "В меню",
    "close": "Закрити",
    "next": "Далі",
    "gotIt": "Зрозуміло",
    "start": "Почати",
    "claim": "Забрати",
    "levelShort": "рів. {n}",
    "tower": "Вежа",
    "tower.hold": "Спробуй втримати перше місце",
    "tower.until": "до призу",
    "packs": "Набори",
    "packs.sub": "Монети і бомби",
    "packs.banner": "Набори",
    "packs.uah": "Набори за гривні",
    "packs.uahSub": "Монети, бомби і жирний вогник",
    "packs.vitrine": "Вітрина",
    "hint": "Підказка",
    "undo": "Скасувати",
    "restart": "Заново",
    "skinBtn": "Скін банки",
    "skinHud": "Скін: {name}",
    "more": "Ще ігри — пілот студії",
    "hud.bomb": "Зірки наповнюють бомбу. 100 ★ = 💣",
    "hud.fire": "Заходь щодня. Вогник множить виграш",
    "hud.tower": "Вежа",
    "set.lead": "Як тобі зручніше грати.",
    "set.leadQuiet": "Ефекти вимкнені — поле спокійніше.",
    "set.lang": "Мова",
    "set.langSub": "Тексти в грі",
    "set.sound": "Звук",
    "set.soundSub": "Краплі і перемога",
    "set.vibe": "Вібрація",
    "set.vibeSub": "Віддача в руці",
    "set.juice": "Ефекти",
    "set.juiceSub": "Бризки і спалахи. Вимкни, якщо гальмує",
    "set.hint": "Підказка на старті",
    "set.hintSub": "Перша банка трохи підстрибне",
    "set.skin": "Скін банок",
    "set.catalog": "Каталог",
    "set.reset": "Скинути прогрес",
    "set.resetSub": "Рівні, монети, скіни — спочатку",
    "set.erase": "Стерти",
    "set.sure": "Точно?",
    "win.got": "Є!",
    "win.done": "Зібрав",
    "win.more": "Далі більше кольорів і довші ходи.",
    "win.double": "Ролик — подвоїти",
    "win.doubleFree": "Без реклами — подвоїти",
    "win.wait": "Секунду…",
    "win.ad": "Ролик…",
    "win.doubled": "Подвоєно",
    "win.share": "Показати",
    "win.tower": "Вежа",
    "win.crown": "Корона твоя",
    "win.point": "Плюс 1 бал. Ти #{place}. До {name} ще {n}.",
    "win.first": "Плюс 1 бал. Ти перший на тижні. Скриня твоя, якщо втримаєш.",
    "win.stage": "Етап закрито.",
    "win.toChest": "{n} / 100 до скрині.",
    "win.bombReady": " Бомба готова!",
    "win.next": "Наступний",
    "win.newChapter": "Нова глава",
    "win.fromOne": "З першого",
    "win.again": "Ще бій",
    "win.story": "В історію",
    "fail.almost": "Майже",
    "fail.stuck": "Тупик",
    "fail.almostText": "Ще одна банка — і колір закрився б. Ти сам долив до краю.",
    "fail.stuckText": "Ходу немає. Сам зібрав пастку — це і є «ще трохи».",
    "fail.risk": "Вогник тут не згорає. Він росте, якщо заходиш щодня.",
    "fail.undo": "Скасувати хід",
    "fail.jar": "Ще банка",
    "fail.keep": "Заново, серія жива",
    "fail.keepPay": "Заново, серія {n} ",
    "fail.give": "Здатися — серія згорить",
    "fail.open": "Відкрити банку ",
    "fail.openOk": "Банки відкриті",
    "lock.title": "Закрита банка",
    "lock.broken": "Зламана банка",
    "lock.frozen": "Заморожена банка",
    "lock.text": "Порожнє місце. Відкриєш — буде куди лити, коли тісно.",
    "lock.open": "Відкрити",
    "lock.charge": "Своя колба",
    "lock.chargeN": "Своя колба · {n}",
    "lock.ad": "Ролик — відкрити",
    "lock.later": "Поки ні",
    "lock.playSo": "Грати так",
    "lock.fix": "Полагодити ",
    "lock.thaw": "Розморозити ",
    "lock.adFix": "Ролик — полагодити",
    "lock.adThaw": "Ролик — розморозити",
    "lock.freeOpen": "Без реклами — відкрити",
    "lock.freeFix": "Без реклами — полагодити",
    "lock.freeThaw": "Без реклами — розморозити",
    "lock.woundBomb": "У тебе зламана банка. Це {name}. Полагодь за монети або ролик.",
    "lock.woundFreeze": "У тебе заморожена банка. Це {name}. Розморозь за монети або ролик.",
    "lock.mustPaint": " Банка з фарбою — треба лагодити.",
    "lock.tight": "Рівень тісний. Без колби нікуди лити.",
    "lock.last": "Остання закрита. Відкриєш — з’явиться порожнє місце.",
    "lock.more": "Ще {n} закритих. Спочатку одну.",
    "lock.pour": " Відкриєш — можна лити далі.",
    "lock.hinder": " Частина замків — перешкода вежі на цей тиждень.",
    "league.title": "Ліга тижня",
    "league.lead": "Ті самі суперники до понеділка. Не онлайн-чат.",
    "league.shop": "Крамниця монет",
    "league.race": "Забіг",
    "map.lead": "Збирай монети і зірки для головної скрині у вежі тут",
    "map.stage": "Сотня {n}. Ті самі 100, вже зліші.",
    "pass.title": "Вежа на замку",
    "pass.call": "Скриня тижня лише для тих, хто назбирав на вхід",
    "pass.wallet": "У гаманці",
    "pass.need": "Вхід — 1000 монет",
    "pass.miss": "Не вистачає монет",
    "pass.short": "Не вистачає {n} монет",
    "pass.ok": "Монет вистачає — можна зайти",
    "pass.buy": "Купити пропуск ",
    "pass.shop": "У крамницю",
    "prize.kicker": "У скрині тижня",
    "tower.score": "Твої очки: {n}",
    "tower.scorePlace": "Твої очки: {n} · #{place}",
    "shop.title": "Крамниця монет",
    "shop.lead": "Трать на колби і на перешкоду іншим. Ролик — лише якщо сам увімкнув.",
    "shop.skins": "Скіни банок",
    "shop.skinsSub": "20 видів. Преміум — за монети",
    "shop.flask": "Запасна колба",
    "shop.flaskSub": "Відкриє закриту банку без ціни рівня",
    "shop.seal": "Печатка на колбу",
    "shop.sealSub": "Звичайні монети. Зупинить ріст очок",
    "shop.undo": "Пачка скасувань",
    "shop.undoSub": "Два скасування в кишеню",
    "shop.ad": "Ролик — монети",
    "shop.watch": "Дивитись",
    "shop.take": "Забрати",
    "shop.adFor": " за перегляд",
    "shop.adFree": " без ролика",
    "shop.have": "У тебе ",
    "shop.have2": " {coins} і {n} запасних колб.",
    "skins.title": "Скіни",
    "skins.lead": "Вісім простих зі скринь. Дванадцять преміум — за монети.",
    "skins.have": "У тебе {owned} / 20. Преміум {prem} / 12. Монет {coins}.",
    "chest.title": "Скриня глави",
    "chest.lead": "За десять рівнів. Ось що всередині.",
    "chest.prizeLead": "Приз за {n} рівнів.",
    "jack.title": "Ти перший!",
    "jack.lead": "Тиждень закрито. Цей приз твій.",
    "jack.word": "за перше місце",
    "intro.stars": "Зірки",
    "intro.starsText": "Збирай зірки, щоб отримати бомбу. Кожні 100 зірок наповнюють ємність — у вежі бомбою можна розірвати колбу супернику.",
    "intro.fire": "Вогник",
    "intro.fireText": "Це буст до заробітку. Заходь щодня — не втрать буст. Щодня вогник +1. З виграшу монет: множення на 0,1 × число вогників.",
    "intro.coins": "Монети і підказка",
    "intro.coinsText": "Монетки — на покупки. Лампочка — підказка ходу. Це і так видно в шапці.",
    "time.dh": "{d}д {h}г",
    "time.hm": "{h}г {m}хв",
    "time.m": "{m} хв",
    "time.home": "{left} до призу",
    "day.1": "день",
    "day.2": "дні",
    "day.5": "днів",
    "league.days": "Ще {n} {word} до нової сітки. Суперники тижня, не живий чат.",
    "race.done": "Забіг рів. {n} · {stars}★ / {moves}",
    "race.wait": "Забіг тижня · рівень {n}",
    "hinder.1": "Перешкода тижня: закрито {n} колба.",
    "hinder.n": "Перешкода тижня: закрито {n} колби.",
    "floor": "поверх",
    "track.tower": "#{place} · очки до понеділка",
    "track.towerEmpty": "Очки вежі",
    "skin.worn": "надіто",
    "skin.yours": "твій",
    "skin.chest": "скриня",
    "skin.default": "Скло",
    "skin.night": "Ніч",
    "skin.mint": "М’ята",
    "skin.rose": "Троянда",
    "skin.sand": "Пісок",
    "skin.ice": "Лід",
    "skin.smoke": "Дим",
    "skin.foam": "Піна",
    "skin.ribbed": "Рельєфні",
    "skin.vase": "Вази",
    "skin.mug": "Кружки",
    "skin.wide": "Широкі",
    "skin.gold": "Золото",
    "skin.honey": "Мед",
    "skin.ocean": "Океан",
    "skin.ember": "Вугілля",
    "skin.lava": "Лава",
    "skin.neon": "Неон",
    "skin.crystal": "Кристал",
    "skin.ink": "Туш",
    "skin.aurora": "Сяйво",
    "skin.royal": "Корона",
    "skin.void": "Порожнеча",
    "skin.myth": "Міф",
    "ch.0": "Перші банки",
    "ch.1": "Три кольори",
    "ch.2": "Смак перемоги",
    "ch.3": "Тісно",
    "ch.4": "Чотири в ряд",
    "ch.5": "П’ять фарб",
    "ch.6": "Тиск",
    "ch.7": "Спека",
    "ch.8": "Шість кольорів",
    "ch.9": "Корона",
    "pack.pack200": "Старт",
    "pack.pack500": "Запас",
    "pack.pack999": "Корона",
    "pack.coins": "монети",
    "pack.bombs": "бомби",
    "pack.fire": "вогник",
    "pack.grn": " грн",
    "pack.loot": "{coins} монет · {bombs} бомб",
    "pack.lootFire": "{coins} монет · {bombs} бомб · вогник ×2",
    "jack.mute": "Тиждень без реклами",
    "jack.mute.sub": "Жодного ролика. Тільки банки.",
    "jack.bombs": "Бомби без дна",
    "jack.bombs.sub": "14 днів кидай скільки влізе.",
    "jack.hints": "Підказки без кінця",
    "jack.hints.sub": "Два тижні будь-яка банка світиться.",
    "jack.coins": "100 000 монет",
    "jack.coins.sub": "Гора. Вистачить на вежу і всі банки.",
    "jack.fire": "Вогник ×5",
    "jack.fire.sub": "Тиждень. Кожен виграш жирний.",
    "jack.skins": "Усі скіни одразу",
    "jack.skins.sub": "Золото, лава, міф — твої.",
    "jack.mix": "Джекпот тижня",
    "jack.mix.sub": "25 000 монет, бомби ∞ на 7 днів і вогонь ×3.",
    "loot.hints": "{n} підказок",
    "loot.skin": "Скін «{name}»",
    "loot.coins": "+{n} монет",
    "loot.boost": "×{mult} монет на {hours} год",
    "loot.stage": "Нова сотня: ті самі 100, вже складніше",
    "loot.skinJar": "Скін «{name}» — вигляд банок",
    "word.hint1": "підказка",
    "word.hint2": "підказки",
    "word.hint5": "підказок",
    "word.coins": "монет",
    "word.hours": "на {n} год",
    "word.skin": "Скін",
    "word.jars": "банок",
    "word.levels": "рівнів",
    "word.undo1": "скасування",
    "word.undoN": "скасувань",
    "word.prize": "Приз",
    "word.chest": "скриня",
    "toast.reset": "Прогрес скинуто",
    "toast.stage": "Сотня {n}. Вже тісніше.",
    "toast.wear": "Надів «{name}»",
    "toast.skinChest": "«{name}» падає зі скрині глави",
    "toast.needCoins": "Потрібно {n} монет",
    "toast.bought": "Купив «{name}»",
    "toast.jackpot": "Приз вежі в тебе",
    "toast.needPass": "Потрібно 1000 монет. Грай рівні — копи.",
    "toast.pass": "Пропуск на тиждень твій. Можна змагатися.",
    "toast.payFail": "Оплата не пройшла",
    "toast.packTest": "Набір «{name}» твій. Коли вийде в Play — {uah} грн.",
    "toast.packOk": "Набір «{name}» твій.",
    "toast.sealTap": "Тисни печатку на гравці.",
    "toast.sealPay": "Печатка — за монети.",
    "toast.bombTap": "Тисни бомбу на гравці.",
    "toast.bombNeed": "Збери зірки, щоб отримати бомбу.",
    "toast.flask": "Запасна колба +1",
    "toast.adFail": "Реклама не відкрилась",
    "toast.lockFirst": "Спочатку пройди рівень {n}",
    "toast.noEmpty": "Порожніх немає. Колба або ролик.",
    "toast.sealHit": "У {name} заморожена банка",
    "toast.bombHit": "У {name} зламана банка",
    "toast.adCoins": "+{n} монет",
    "wound.paintBomb": "У тебе банка з фарбою зламана. Це {name}. Треба лагодити.",
    "wound.paintFreeze": "У тебе банка з фарбою заморожена. Це {name}. Треба лагодити.",
    "wound.bomb": "У тебе зламана банка. Це {name}",
    "wound.freeze": "У тебе заморожена банка. Це {name}",
    "wound.must": "банка з фарбою — треба лагодити",
    "wound.jar": "банка {n}",
    "aria.bomb": "Бомба",
    "aria.seal": "Печатка",
    "aria.locked": "закрита банка",
    "aria.pack": "Набір «{name}» · {uah} грн",
    "tip.bomb": "Бомба ламає йому банку. Бомби копляться із зірок.",
    "tip.seal": "Печатка заморожує йому банку. Платиш монетами.",
    "share.line": "Глава «{ch}» · рівень {n} · серія {streak} · ліга #{place}",
    "share.chapter": "Глава",
    "share.level": "Рівень {n}",
    "share.streak": "Серія {n}",
    "share.league": "Ліга #{n}",
    "share.foot": "Сам зібрав. Без підказки на скріні.",
  },
  en: {
    "app.title": "Jars",
    "app.tag": "Pour the color. Don't leave yourself no move.",
    "you": "You",
    "you.letter": "Y",
    "rival": "Rival",
    "on": "On",
    "off": "Off",
    "back": "Back",
    "menu": "Menu",
    "home": "Home",
    "settings": "Settings",
    "premium": "Premium",
    "skins": "Skins",
    "play": "Play",
    "toGame": "To game",
    "toMenu": "Menu",
    "close": "Close",
    "next": "Next",
    "gotIt": "Got it",
    "start": "Start",
    "claim": "Claim",
    "levelShort": "lv. {n}",
    "tower": "Tower",
    "tower.hold": "Try to hold first place",
    "tower.until": "to prize",
    "packs": "Packs",
    "packs.sub": "Coins and bombs",
    "packs.banner": "Packs",
    "packs.uah": "Packs for hryvnia",
    "packs.uahSub": "Coins, bombs and a fat flame",
    "packs.vitrine": "Store",
    "hint": "Hint",
    "undo": "Undo",
    "restart": "Retry",
    "skinBtn": "Jar skin",
    "skinHud": "Skin: {name}",
    "more": "More games — studio pilot",
    "hud.bomb": "Stars fill a bomb. 100 ★ = 💣",
    "hud.fire": "Come every day. The flame multiplies wins",
    "hud.tower": "Tower",
    "set.lead": "Play the way that feels right.",
    "set.leadQuiet": "Effects off — the board is calmer.",
    "set.lang": "Language",
    "set.langSub": "Game texts",
    "set.sound": "Sound",
    "set.soundSub": "Drops and wins",
    "set.vibe": "Vibration",
    "set.vibeSub": "A tap in the hand",
    "set.juice": "Effects",
    "set.juiceSub": "Splashes and flashes. Turn off if it lags",
    "set.hint": "Hint on start",
    "set.hintSub": "The first jar gives a little hop",
    "set.skin": "Jar skins",
    "set.catalog": "Catalog",
    "set.reset": "Reset progress",
    "set.resetSub": "Levels, coins, skins — from scratch",
    "set.erase": "Erase",
    "set.sure": "Sure?",
    "win.got": "Yes!",
    "win.done": "Sorted",
    "win.more": "Next ones have more colors and longer pours.",
    "win.double": "Ad — double",
    "win.doubleFree": "No ads — double",
    "win.wait": "One sec…",
    "win.ad": "Ad…",
    "win.doubled": "Doubled",
    "win.share": "Show",
    "win.tower": "Tower",
    "win.crown": "The crown is yours",
    "win.point": "Plus 1 point. You are #{place}. {n} more to {name}.",
    "win.first": "Plus 1 point. You are first this week. Hold it for the chest.",
    "win.stage": "Stage cleared.",
    "win.toChest": "{n} / 100 to the chest.",
    "win.bombReady": " Bomb ready!",
    "win.next": "Next",
    "win.newChapter": "New chapter",
    "win.fromOne": "From one",
    "win.again": "Another fight",
    "win.story": "To the story",
    "fail.almost": "Almost",
    "fail.stuck": "Stuck",
    "fail.almostText": "One more jar and the color would have closed. You poured it full yourself.",
    "fail.stuckText": "No move left. You built the trap — that's the “almost”.",
    "fail.risk": "The flame doesn't burn here. It grows if you come every day.",
    "fail.undo": "Undo move",
    "fail.jar": "One more jar",
    "fail.keep": "Retry, streak lives",
    "fail.keepPay": "Retry, streak {n} ",
    "fail.give": "Give up — streak dies",
    "fail.open": "Open a jar ",
    "fail.openOk": "Jars are open",
    "lock.title": "Locked jar",
    "lock.broken": "Broken jar",
    "lock.frozen": "Frozen jar",
    "lock.text": "Empty space. Open it — you'll have somewhere to pour when it's tight.",
    "lock.open": "Open",
    "lock.charge": "Your flask",
    "lock.chargeN": "Your flask · {n}",
    "lock.ad": "Ad — open",
    "lock.later": "Not now",
    "lock.playSo": "Play like this",
    "lock.fix": "Fix ",
    "lock.thaw": "Unfreeze ",
    "lock.adFix": "Ad — fix",
    "lock.adThaw": "Ad — unfreeze",
    "lock.freeOpen": "No ads — open",
    "lock.freeFix": "No ads — fix",
    "lock.freeThaw": "No ads — unfreeze",
    "lock.woundBomb": "Your jar is broken. That was {name}. Fix it with coins or an ad.",
    "lock.woundFreeze": "Your jar is frozen. That was {name}. Unfreeze it with coins or an ad.",
    "lock.mustPaint": " A paint jar must be fixed.",
    "lock.tight": "The level is tight. No flask — nowhere to pour.",
    "lock.last": "Last lock. Open it — an empty slot appears.",
    "lock.more": "{n} still locked. Open one first.",
    "lock.pour": " Open it — you can pour again.",
    "lock.hinder": " Some locks are this week's tower hindrance.",
    "league.title": "Week league",
    "league.lead": "Same rivals until Monday. Not a live chat.",
    "league.shop": "Coin shop",
    "league.race": "Race",
    "map.lead": "Collect coins and stars for the main chest in the tower here",
    "map.stage": "Hundred {n}. Same 100, meaner.",
    "pass.title": "Tower is locked",
    "pass.call": "The weekly chest is for those who saved up to enter",
    "pass.wallet": "In the wallet",
    "pass.need": "Entry — 1000 coins",
    "pass.miss": "Not enough coins",
    "pass.short": "Need {n} more coins",
    "pass.ok": "Enough coins — you can enter",
    "pass.buy": "Buy pass ",
    "pass.shop": "To shop",
    "prize.kicker": "In this week's chest",
    "tower.score": "Your points: {n}",
    "tower.scorePlace": "Your points: {n} · #{place}",
    "shop.title": "Coin shop",
    "shop.lead": "Spend on flasks and on slowing others. Ads only if you tap them.",
    "shop.skins": "Jar skins",
    "shop.skinsSub": "20 looks. Premium costs coins",
    "shop.flask": "Spare flask",
    "shop.flaskSub": "Opens a locked jar without the level price",
    "shop.seal": "Jar seal",
    "shop.sealSub": "Regular coins. Stops their score from growing",
    "shop.undo": "Undo pack",
    "shop.undoSub": "Two undos in the pocket",
    "shop.ad": "Ad — coins",
    "shop.watch": "Watch",
    "shop.take": "Take",
    "shop.adFor": " for a watch",
    "shop.adFree": " no ad",
    "shop.have": "You have ",
    "shop.have2": " {coins} and {n} spare flasks.",
    "skins.title": "Skins",
    "skins.lead": "Eight simple ones from chests. Twelve premium for coins.",
    "skins.have": "You have {owned} / 20. Premium {prem} / 12. Coins {coins}.",
    "chest.title": "Chapter chest",
    "chest.lead": "For ten levels. Here's what's inside.",
    "chest.prizeLead": "Prize for {n} levels.",
    "jack.title": "You're first!",
    "jack.lead": "The week is over. This prize is yours.",
    "jack.word": "for first place",
    "intro.stars": "Stars",
    "intro.starsText": "Collect stars to get a bomb. Every 100 stars fill the meter — in the tower a bomb can crack a rival's flask.",
    "intro.fire": "Flame",
    "intro.fireText": "It's a payout boost. Come every day — don't lose it. Each day the flame +1. Coins from a win: times 0.1 × flame count.",
    "intro.coins": "Coins and hint",
    "intro.coinsText": "Coins buy stuff. The bulb is a move hint. You can already see that in the header.",
    "time.dh": "{d}d {h}h",
    "time.hm": "{h}h {m}m",
    "time.m": "{m} min",
    "time.home": "{left} to prize",
    "day.1": "day",
    "day.2": "days",
    "day.5": "days",
    "league.days": "{n} {word} left until a new grid. Weekly rivals, not a live chat.",
    "race.done": "Race lv. {n} · {stars}★ / {moves}",
    "race.wait": "Week race · level {n}",
    "hinder.1": "Week hindrance: {n} flask locked.",
    "hinder.n": "Week hindrance: {n} flasks locked.",
    "floor": "floor",
    "track.tower": "#{place} · points until Monday",
    "track.towerEmpty": "Tower points",
    "skin.worn": "on",
    "skin.yours": "yours",
    "skin.chest": "chest",
    "skin.default": "Glass",
    "skin.night": "Night",
    "skin.mint": "Mint",
    "skin.rose": "Rose",
    "skin.sand": "Sand",
    "skin.ice": "Ice",
    "skin.smoke": "Smoke",
    "skin.foam": "Foam",
    "skin.ribbed": "Ribbed",
    "skin.vase": "Vases",
    "skin.mug": "Mugs",
    "skin.wide": "Wide",
    "skin.gold": "Gold",
    "skin.honey": "Honey",
    "skin.ocean": "Ocean",
    "skin.ember": "Ember",
    "skin.lava": "Lava",
    "skin.neon": "Neon",
    "skin.crystal": "Crystal",
    "skin.ink": "Ink",
    "skin.aurora": "Glow",
    "skin.royal": "Crown",
    "skin.void": "Void",
    "skin.myth": "Myth",
    "ch.0": "First jars",
    "ch.1": "Three colors",
    "ch.2": "Taste of a win",
    "ch.3": "Tight",
    "ch.4": "Four in a row",
    "ch.5": "Five paints",
    "ch.6": "Pressure",
    "ch.7": "Heat",
    "ch.8": "Six colors",
    "ch.9": "Crown",
    "pack.pack200": "Start",
    "pack.pack500": "Stock",
    "pack.pack999": "Crown",
    "pack.coins": "coins",
    "pack.bombs": "bombs",
    "pack.fire": "flame",
    "pack.grn": " UAH",
    "pack.loot": "{coins} coins · {bombs} bombs",
    "pack.lootFire": "{coins} coins · {bombs} bombs · flame ×2",
    "jack.mute": "A week with no ads",
    "jack.mute.sub": "Not a single ad. Just jars.",
    "jack.bombs": "Endless bombs",
    "jack.bombs.sub": "14 days, throw as many as you want.",
    "jack.hints": "Endless hints",
    "jack.hints.sub": "Two weeks any jar lights up.",
    "jack.coins": "100,000 coins",
    "jack.coins.sub": "A pile. Enough for the tower and every jar.",
    "jack.fire": "Flame ×5",
    "jack.fire.sub": "A week. Every win is fat.",
    "jack.skins": "Every skin at once",
    "jack.skins.sub": "Gold, lava, myth — yours.",
    "jack.mix": "Week jackpot",
    "jack.mix.sub": "25,000 coins, bombs ∞ for 7 days and fire ×3.",
    "loot.hints": "{n} hints",
    "loot.skin": "Skin “{name}”",
    "loot.coins": "+{n} coins",
    "loot.boost": "×{mult} coins for {hours}h",
    "loot.stage": "New hundred: same 100, harder",
    "loot.skinJar": "Skin “{name}” — jar look",
    "word.hint1": "hint",
    "word.hint2": "hints",
    "word.hint5": "hints",
    "word.coins": "coins",
    "word.hours": "for {n}h",
    "word.skin": "Skin",
    "word.jars": "jars",
    "word.levels": "levels",
    "word.undo1": "undo",
    "word.undoN": "undos",
    "word.prize": "Prize",
    "word.chest": "chest",
    "toast.reset": "Progress wiped",
    "toast.stage": "Hundred {n}. Tighter already.",
    "toast.wear": "Wearing “{name}”",
    "toast.skinChest": "“{name}” drops from the chapter chest",
    "toast.needCoins": "Need {n} coins",
    "toast.bought": "Bought “{name}”",
    "toast.jackpot": "Tower prize is yours",
    "toast.needPass": "Need 1000 coins. Play levels — save up.",
    "toast.pass": "Week pass is yours. You can compete.",
    "toast.payFail": "Payment didn't go through",
    "toast.packTest": "Pack “{name}” is yours. In Play it will be {uah} UAH.",
    "toast.packOk": "Pack “{name}” is yours.",
    "toast.sealTap": "Tap the seal on a player.",
    "toast.sealPay": "The seal costs coins.",
    "toast.bombTap": "Tap the bomb on a player.",
    "toast.bombNeed": "Collect stars to get a bomb.",
    "toast.flask": "Spare flask +1",
    "toast.adFail": "The ad didn't open",
    "toast.lockFirst": "Clear level {n} first",
    "toast.noEmpty": "No empties. Flask or an ad.",
    "toast.sealHit": "{name}'s jar is frozen",
    "toast.bombHit": "{name}'s jar is broken",
    "toast.adCoins": "+{n} coins",
    "wound.paintBomb": "Your paint jar is broken. That was {name}. You must fix it.",
    "wound.paintFreeze": "Your paint jar is frozen. That was {name}. You must fix it.",
    "wound.bomb": "Your jar is broken. That was {name}",
    "wound.freeze": "Your jar is frozen. That was {name}",
    "wound.must": "paint jar — must fix",
    "wound.jar": "jar {n}",
    "aria.bomb": "Bomb",
    "aria.seal": "Seal",
    "aria.locked": "locked jar",
    "aria.pack": "Pack “{name}” · {uah} UAH",
    "tip.bomb": "A bomb breaks their jar. Bombs come from stars.",
    "tip.seal": "A seal freezes their jar. You pay coins.",
    "share.line": "Chapter “{ch}” · level {n} · streak {streak} · league #{place}",
    "share.chapter": "Chapter",
    "share.level": "Level {n}",
    "share.streak": "Streak {n}",
    "share.league": "League #{n}",
    "share.foot": "Sorted it myself. No hint on the shot.",
  },
};
